spring:
  config:
     activate:
        on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/egs
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1
  jpa:
    show-sql: true
  sql:
    init:
      platform: postgresql

application:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000